<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

	<PropertyGroup>
		<ModdableToolGroupsPath Condition="'$(ModdableToolGroupsPath)'==''">$(GameModsFolder)ModdableToolGroups\version-1.1\**\*.dll</ModdableToolGroupsPath>
	</PropertyGroup>

	<ItemGroup>
		<Using Include="ConfigurableToolGroups" />
		<Using Include="ConfigurableToolGroups.Services" />
		<Using Include="ConfigurableToolGroups.Specs" />
		<Using Include="ConfigurableToolGroups.Models" />
		<Using Include="ConfigurableToolGroups.UI" />

		<Reference Include="$(ModdableToolGroupsPath)" Private="false" />
	</ItemGroup>

</Project>
